apiVersion: v1
kind: Namespace
metadata:
  name: demo

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: special-config
  namespace: demo
data:
  special.level: this is the configMap default value
